import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
    String kid = "";
    int num = 1;
    int x = 0;
    int fam2 = 0;
    int fam3 = 0;
    int fam4 = 0;
    int y = 0;


while (x<T){
    x++;
    double ran1 = Math.random();
    double ran2 = Math.random();
    

    /////////////////////////////
    if (ran1 >= 0.5) {
        kid = kid + "g";} 
    else {kid = kid + "b";} 
        
    while ((ran1 < 0.5 && ran2 < 0.5) || (ran1 >= 0.5 && ran2 >= 0.5)){
        if(ran2>=0.5){
            kid = kid + " g";}
        else{kid = kid + " b";}
            ran2 = Math.random();
            num++;}

    if(ran2>=0.5){ 
        kid = kid + " g";
        num++;}
    else{kid = kid + " b";
        num++;}

 ///////////////////////////////////       
    if (num == 2) {
        fam2++;
    }
    if (num == 3) {
        fam3++;
    }
    if (num >= 4) {
        fam4++;
    }
    
    y = y + num;
    num = 1;
}
double av = y/T;

    System.out.println("Avrage: "+ av +" children to get at least one of each gender.");
    System.out.println("Number of families with 2 children: "+fam2);
    System.out.println("Number of families with 3 children: "+fam3);
    System.out.println("Number of families with 4 or more children: "+fam4);
    
    if (fam2>fam3 && fam2>fam4){
        System.out.println("The most common number of children is "+2+ ".");}
    else if (fam3>fam2 && fam3>fam4){
        System.out.println("The most common number of children is "+3+ ".");}
    else{
        System.out.println("The most common number of children is "+4+ " or more.");}
    
}
}
